### ISSUE TITLE
FAQ: Calculated Field complains if you attempt to pass direct fields

### ISSUE THREAD

**Issue by slopp** [rstudio/plumbertableau#39]
If you attempt something like this:

```
SCRIPT_STR("/penguins/species", [Flipper Length Mm],[Body Mass G])
```

You may get an error like:

```
all fields must be aggregate or constant
```

To fix, you use a "fake" function, e.g.:

``
SCRIPT_STR("/penguins/species", ATTR([Flipper Length Mm]),ATTR([Body Mass G]))
```

This is likely going to be a very common FAQ that we may need to document.

**Comment by blairj09** [comment]
This is addressed here: https://github.com/rstudio/plumbertableau/blob/ff03e9c3c208fcfacc02e24dadd08d17bd9580f1/vignettes/tableau-developer-guide.Rmd#L48
