### ISSUE TITLE
OpenAPI documentation `curl` command seems to mix Tableau-style and regular-style invocation

### ISSUE THREAD

**Issue by toph-allen** [rstudio/plumbertableau#43]
I'm running the `stringutils` example, and I see this CURL command under "Try it out":

<img width="864" alt="Screen Shot 2021-07-16 at 3 59 08 PM" src="https://user-images.githubusercontent.com/3117884/126002382-5aa6d433-150e-4b08-82c8-5dc7a28db4f5.png">

```
curl -X POST "http://127.0.0.1:8215/lowercase" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"script\":\"/lowercase\",\"data\":{\"_arg1\":[\"string\"]}}"
```

Notice that the URL's path component is `/lowercase`, but the JSON blob also contains the redundant `"script": "lowercase"`. This doesn't match calls we'd expect from Tableau, which would, unless I'm having a brain fart, be more like:

```
curl -X POST "http://127.0.0.1:8215/evaluate" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"script\":\"/lowercase\",\"data\":{\"_arg1\":[\"string\"]}}"
```

Probably best to go one way or the other? Or am I overthinking this?

**Comment by blairj09** [comment]
I agree it would be nice to have a "true' Tableau request here. However, this curl command is autogenerated from the OpenAPI spec, and from what I can see, we couldn't modify it without making a drastic departure from standard OpenAPI behavior. Perhaps this is best handled with documentation?

**Comment by toph-allen** [comment]
Hmm, we should probably document it. I don't think it's that much of a big deal. What this is really about is the payload, right? The package handles routing requests to `/evaluate` to `/script`, but the data payload is handled the same in either case. Might be worth putting into an appendix or note in the docs at some point.

**Comment by blairj09** [comment]
Yes, it's really about ensuring the payload is formatted correctly, with the `curl` command does :grin: I'll add a line to the documentation

**Comment by blairj09** [comment]
Addressed here: https://github.com/rstudio/plumbertableau/pull/66/commits/a7e161b4a202fe6a4da64893f542ca3a0a288e91
