### ISSUE TITLE
rstudioconnect a requirement?

### ISSUE THREAD

**Issue by klar-C** [rstudio/plumbertableau#77]
Hi - 

Is it possible to run this without rstudioconnect?

I tried to follow the steps in the introduction but getting the following error when starting up plumber:
_Verbose logging is off. To enable it please set the environment variable `DEBUGME` to include `plumbertableau`.
Error in route$getFunc() : attempt to apply non-function_

Any help would be appreciated.

**Comment by blairj09** [comment]
Yes RStudio Connect is not a requirement. If you can share the definition of your plumber file to help us reproduce the issue, we'll be better able to help identify what's happening.

**Comment by blairj09** [comment]
@klar-C are there any further updates to this issue?

**Comment by klar-C** [comment]
No - unfortunately we had to put the project on a backburner. Closing it to keep your issue list clean. Apologies for not being more responsive here.
